=== JonasBerx/XML_Bases_IPL/src/films/films.dtd
<!ELEMENT films (film+)>
<!ELEMENT film (photo?,titre,annee,realisateur,casting,synopsis)>
<!ATTLIST film lang (fr|en) #REQUIRED>
<!ELEMENT photo EMPTY>
<!ATTLIST photo href CDATA #REQUIRED>
<!ELEMENT casting (acteur*)>
<!ELEMENT acteur (#PCDATA)>
<!ATTLIST acteur id ID #IMPLIED personnage CDATA #REQUIRED>
<!ELEMENT synopsis (#PCDATA|perso)*>
<!ELEMENT perso EMPTY>
<!ATTLIST perso ref IDREF #REQUIRED>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT annee (#PCDATA)>
<!ELEMENT realisateur (#PCDATA)>

=== JonasBerx/XML_Bases_IPL/src/films/film5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE films SYSTEM "films.dtd" >
<films>
    <film lang="fr">
        <photo href="photos/demineur.jpg" />
        <titre>Requiem for a Dream</titre>
        <annee>2000</annee>
        <realisateur>Darren Aronofsky</realisateur>
        <casting>
            <acteur id="harry" personnage="Harry Goldfarb">Jared
                Leto</acteur>
        </casting>
        <synopsis>
            <perso ref="harry"/>, sa petite amie, et son meilleur ami Tyrone
            rêvent d’un monde meilleur et d’une vie plus facile.
        </synopsis>
    </film>
    <film lang="en">
        <photo href="photos/cool.jpg"/>
        <titre>Requiem for a Dream</titre>
        <annee>2000</annee>
        <realisateur>Darren Aronofsky</realisateur>
        <casting></casting>
        <synopsis>
            Harry, sa petite amie, et son meilleur ami Tyrone
            rêvent d’un monde meilleur et d’une vie plus facile.
        </synopsis>
    </film>
</films>

=== JonasBerx/XML_Bases_IPL/src/films/film2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE films SYSTEM "films.dtd" >
<films>
    <film lang="fr">
        <titre>Requiem for a Dream</titre>
        <annee>2000</annee>
        <realisateur>Darren Aronofsky</realisateur>
        <casting>
            <acteur id="harry" personnage="Harry Goldfarb">Jared Leto</acteur>
        </casting>
        <synopsis>
            <perso ref="harry"/>, sa petite amie, et son meilleur ami Tyrone
            rêvent d’un monde meilleur et d’une vie plus facile. Ils passent
            leurs journées à se droguer, pour être en parfaite lévitation,
            là où ils se sentent invulnérables et tout simplement heureux.
        </synopsis>
    </film>
</films>

=== JonasBerx/XML_Bases_IPL/src/films/film1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "films.dtd" >
<film lang="fr">
    <photo href="photos/demineur.jpg" />
    <titre>Requiem for a Dream</titre>
    <annee>2000</annee>
    <realisateur>Darren Aronofsky</realisateur>
    <casting>
        <acteur id="harry" personnage="Harry Goldfarb">Jared Leto</acteur>
        <acteur id="sara" personnage="Sara Goldfarb">Ellen Burstyn</acteur>
        <acteur id="mari" personnage="Marianne Silver">Jennifer
            Connelly</acteur>
    </casting>
    <synopsis>
        <perso ref="harry"/>, sa petite amie <perso ref="mari"/>, et son meilleur
        ami Tyrone rêvent d’un monde meilleur et d’une vie plus facile. Ils
        passent leurs journées à se droguer, pour être en parfaite lévitation, là
        où ils se sentent invulnérables et tout simplement heureux.
    </synopsis>
</film>

=== JonasBerx/XML_Bases_IPL/src/films/film4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE film SYSTEM "films.dtd" >
<film lang="fr">
    <titre>Requiem for a Dream</titre>
    <annee>2000</annee>
    <realisateur>Darren Aronofsky</realisateur>
    <casting>
        <acteur personnage="Harry Goldfarb" id="harry" >Jared Leto</acteur>
        <acteur id="sara" personnage="Sara Goldfarb">Ellen Burstyn</acteur>
        <acteur personnage="Marianne Silver" id="mari" >Jennifer Connelly</acteur>
    </casting>
    <synopsis>
    </synopsis>
</film>
