=== JonasBerx/XML_Bases_IPL/src/sem03/exo02/library.dtd
<!ELEMENT track_ID (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT genre (#PCDATA)>
<!--<!ATTLIST genretype (Hip Hop|Rock|Metal|Pop)>-->
<!ELEMENT comments (#PCDATA)>
<!ATTLIST comments author CDATA #REQUIRED>
<!ELEMENT song (track_ID,name,artist?,album?,genre?,comments*)>
<!ELEMENT list (track_ID+)>
<!ATTLIST list name ID #REQUIRED)>
<!ELEMENT songlist (song+)>
<!ELEMENT playlists (list*)>
<!ELEMENT library (songlist, playlists?)>

=== JonasBerx/XML_Bases_IPL/src/sem03/exo02/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--EXO 02 XML for XSD-->
<!--<library-->
<!--xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
<!--xsi:noNamespaceSchemaLocation="library.xsd">-->
<!-- EXO 03 XSD to DTD-->
<!DOCTYPE library SYSTEM
    "library.dtd">
<library>

    <songlist>
        <song>
            <track_ID>1</track_ID>
            <name>Track 1</name>
            <artist>Artist</artist>
            <album>Album</album>
            <genre>Rock</genre>
            <comments author="Jonas">
                Nice
            </comments>
            <comments author="Jonas">
                Nicee
            </comments>
        </song>
        <song>
            <track_ID>2</track_ID>
            <name>Track 1</name>
            <album>Artist2</album>
            <genre>Rock</genre>
            <comments author="Jonas">
                Nicer
            </comments>
        </song>
    </songlist>
    <playlists>
        <list name="list1">
            <track_ID>1</track_ID>
            <track_ID>2</track_ID>
        </list>
    </playlists>
</library>
